DATA_ROOT: '../datasets/'
LOGS_ROOT: '../logs/'


MODEL:
  # architecture
  backbone: {'generator', 'discriminator'}

  # cycle_gan or spgan
  metric_net: True

  dsbn: True


DATA:

  height: 256
  width: 256
  norm_mean: [0.5, 0.5, 0.5]
  norm_std: [0.5, 0.5, 0.5]

  TRAIN:
    # augmentation
    is_autoaug: False

    is_flip: True
    flip_prob: 0.5

    is_pad: False
    pad_size: 10

    is_blur: False
    blur_prob: 0.5

    is_erase: False
    erase_prob: 0.5

    # dual augmentation for MMT
    is_mutual_transform: False
    mutual_times: 2

  TEST:
    height: 256
    width: 128


TRAIN:
  seed: 1
  deterministic: True

  # datasets
  datasets: {'market1501': 'trainval', 'dukemtmcreid': 'trainval'}

  unsup_dataset_indexes: []

  epochs: 70
  iters: 400


  LOSS:
    losses: {'adversarial': 1., 'cycle_consistent': 10., 'identity': 5., 'contrastive': 2.}
    margin: 2

  # sampler
  SAMPLER:
    num_instances: 4
    is_shuffle: True

  # data loader
  LOADER:
    samples_per_gpu: 1
    workers_per_gpu: 2

  # optim
  OPTIM:
    optim: 'adam'
    lr: 0.0002
    adam_beta1: 0.5

  SCHEDULER:
    lr_scheduler: 'warmup_multi_step'
    stepsize: [20, 40]
    gamma: 0.1
    warmup_factor: 0.01
    warmup_steps: 10